# jobs:
#   run_tests:
#     runs-on: ubuntu-20.04
#     steps:
#     - uses: actions/checkout@v2
#     - name: Setup dependencies
#       run: |
#         apt install imagemagick
#       shell: bash
#     - name: Run script file
#       run: |
#          chmod +x ./wix-cli.sh
#          ./wix-cli.sh img_stdout
#       shell: bash
#     - name: Commit image


# This is a basic workflow to help you get started with Actions

name: Generate Command Output Image

# Controls when the action will run. Triggers the workflow on push events
on:
  push:
    branches: [ master, bash-to-image ]
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v3

    # Setup apt dependencies
    - name: Setup dependencies
      run: |
        sudo apt install imagemagick
        sudo sed -i 's/\(<policy domain="resource" name="width" value="\)[^"]*/\1160KP/' /etc/ImageMagick-6/policy.xml
        sudo sed -i 's/\(<policy domain="resource" name="height" value="\)[^"]*/\1160KP/' /etc/ImageMagick-6/policy.xml
      shell: bash

    # Run the script
    - name: Run script file
      run: |
        chmod +x ./wix-cli.sh
        ./wix-cli.sh img_stdout
      shell: bash

    # Commit and push changes
    - name: Commit changes
      run: |
        git config --local user.name "hwixley"
        git config --local user.email "hwixley1@gmail.com"
        git add yml-test.png
        git commit -m "Update wix command output"
        git push